/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vavi_awt_image_resample_FfmpegResampleOp */

#ifndef _Included_vavi_awt_image_resample_FfmpegResampleOp
#define _Included_vavi_awt_image_resample_FfmpegResampleOp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vavi_awt_image_resample_FfmpegResampleOp
 * Method:    filterInternal
 * Signature: (Ljava/lang/Object;IIIILjava/lang/Object;IIIII)V
 */
JNIEXPORT void JNICALL Java_vavi_awt_image_resample_FfmpegResampleOp_filterInternal
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
